# Main Jekyll Configuration file.
#
# Jekyll needs to be restarted if you make any changes.
# For more information see the documentation.

# Basic site settings.
locale: "nl_NL"
timezone: Europe/Amsterdam
domain: "ieni.org"

# Page content variables.
title: "Vakvereniging i&amp;i"
short: "i&amp;i"
description: "Vakvereniging i&amp;i maakt zich sterk voor een structureel aanbod van kwalitatief
hoogwaardig onderwijs ten behoeve van informatica en digitale geletterdheid op alle basis- en
middelbare scholen in Nederland. Iedereen die zich vanuit welke functie dan ook betrokken voelt
bij informatica en digitale geletterdheid in het onderwijs verwelkomen wij graag als lid."
legal: "Vereniging voor Informatiekunde en Informatietechnologie in Onderwijs"
kvk: "KvK 40481134 te Utrecht"

# Landing page hero variables.
hero:
  title: "Informatica is de Toekomst."
  lead: "Vakvereniging voor informatica & digitale geletterdheid in het Nederlands Onderwijs."

# Social variables.
twitter: "@ieni"
linkedin: "company/1526376"
linkedingroup: "groups/72298"

# Brand logos and icon paths.
logo:
  dark: "/assets/img/brand/icon-500-black.svg"
  light: "/assets/img/brand/icon-500-white.svg"
header:
  dark: "/assets/img/brand/header-dark.svg"
  light: "/assets/img/brand/header-light.svg"
icon:
  x32: "/assets/img/brand/icon-32.jpg"
  x180: "/assets/img/brand/icon-180.jpg"
  x192: "/assets/img/brand/icon-192.jpg"
  x270: "/assets/img/brand/icon-270.jpg"

# Global site defaults.
defaults:
  page_header: "/assets/img/content/default_page_header.jpg"

# API credentials / Site Keys.
# Keys are whitelisted for this specific domain and intended for front-end
# usage. They can thus be safely committed to this public repository.
credentials:
  postcode: "fa930f80-b571-4796-8246-6fb93c5d23df"

# Jekyll collections for pagination.
# For more information on collections see the Jekyll documentation.
collections:
  pages:
    output: true
    permalink: /:title
  posts:
    permalink: /nieuws/:title/
  projects:
    output: true
    permalink: /projecten/:title/
  team:
    output: false
